// This file is generated by scripts/generate-page-routes.mjs.
// Do not edit directly.

import {
  brandRouteHref,
  encodeRouteSegment,
  withRouteSearch,
  type RouteHref,
  type RouteHrefOptions
} from '@/framework/page-routes.ts'

export const pageRouteDefinitions = [
  {
    file: './routes/about/page.tsx',
    key: 'about',
    pattern: '/about',
    segments: ['about'] as const
  },
  {
    file: './routes/blog/[slug]/page.tsx',
    key: 'blogSlug',
    pattern: '/blog/[slug]',
    segments: ['blog', '[slug]'] as const
  },
  {
    file: './routes/dashboard/page.tsx',
    key: 'dashboard',
    pattern: '/dashboard',
    segments: ['dashboard'] as const
  },
  {
    file: './routes/login/page.tsx',
    key: 'login',
    pattern: '/login',
    segments: ['login'] as const
  },
  { file: './routes/page.tsx', key: 'home', pattern: '/', segments: [] as const }
] as const

export type PageRouteDefinition = (typeof pageRouteDefinitions)[number]
export type PageRouteKey = PageRouteDefinition['key']
export type PageRoutePattern = PageRouteDefinition['pattern']

export type PageRouteParams<P extends PageRoutePattern = PageRoutePattern> = P extends '/about'
  ? Record<string, never>
  : P extends '/blog/[slug]'
    ? { slug: string }
    : P extends '/dashboard'
      ? Record<string, never>
      : P extends '/login'
        ? Record<string, never>
        : P extends '/'
          ? Record<string, never>
          : never

export type PageRouteHref<P extends PageRoutePattern = PageRoutePattern> = RouteHref<P>

export const pageRoutes = {
  about: {
    key: 'about',
    pattern: '/about' as const,
    href(options?: RouteHrefOptions) {
      return brandRouteHref<'/about'>(withRouteSearch(`/about`, options?.search))
    }
  },
  blogSlug: {
    key: 'blogSlug',
    pattern: '/blog/[slug]' as const,
    href(params: { slug: string }, options?: RouteHrefOptions) {
      return brandRouteHref<'/blog/[slug]'>(
        withRouteSearch(`/blog/${encodeRouteSegment(params.slug)}`, options?.search)
      )
    }
  },
  dashboard: {
    key: 'dashboard',
    pattern: '/dashboard' as const,
    href(options?: RouteHrefOptions) {
      return brandRouteHref<'/dashboard'>(withRouteSearch(`/dashboard`, options?.search))
    }
  },
  login: {
    key: 'login',
    pattern: '/login' as const,
    href(options?: RouteHrefOptions) {
      return brandRouteHref<'/login'>(withRouteSearch(`/login`, options?.search))
    }
  },
  home: {
    key: 'home',
    pattern: '/' as const,
    href(options?: RouteHrefOptions) {
      return brandRouteHref<'/'>(withRouteSearch('/', options?.search))
    }
  }
} as const
